language: node_js
sudo: required

branches:
  only:
    - develop
    - travis

matrix:
  include:

    # WINDOWS cross-built from linux
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=win
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - nsis
          sources:
            - mono
      before_install:
        - sudo dpkg --add-architecture i386 && sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        - sudo apt-get update -q
        - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8
      after_script:
        - makensis -V3 windows-installer.nsi


    # LINUX
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=linux
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib

    # MAC
    - os: osx
      osx_image: xcode8.1
      env:
          - GULP_PLATFORM=mac
      node_js: 6
      before_install:
        - npm install -g gulp yarn

cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.electron
    - $HOME/.cache

install:
  - PATH=$PATH:$HOME/.meteor && curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh
  - npm install -g meteor-build-client electron@1.3.5
  - yarn

script:
  - travis_wait 60 gulp mist --platform $GULP_PLATFORM

after_success:
  - gulp mist-checksums --platform $GULP_PLATFORM

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33972d9e627a142c57a6
    on_success: change
    on_failure: always
    on_start: never
