language: node_js
sudo: required

branches:
  only:
    - develop
    - master

matrix:
  include:

    # WINDOWS cross-built from linux
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=win
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - nsis
          sources:
            - mono
      before_install:
        - sudo dpkg --add-architecture i386 && sudo add-apt-repository ppa:ubuntu-wine/ppa -y
        - sudo apt-get update -q
        - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8
      after_script:
        - makensis -V2 scripts/windows-installer.nsi


    # LINUX
    - os: linux
      dist: trusty
      env:
          - GULP_PLATFORM=linux
      node_js: 6
      addons:
        apt:
          packages:
            - icnsutils
            - graphicsmagick
            - xz-utils
            - gcc-multilib
            - g++-multilib

    # MAC
    - os: osx
      osx_image: xcode8  # currently macOS 10.11 (>= xcode8.1) doesn't support electron-builder codesigning (https://github.com/electron-userland/electron-builder/issues/820#issuecomment-267777060)
      env:
          - GULP_PLATFORM=mac
      node_js: 6
      before_install:
        - brew update
        - brew install gnu-tar libicns graphicsmagick xz

cache:
  yarn: true

install:
  - PATH=$PATH:$HOME/.meteor && curl -L https://raw.githubusercontent.com/arunoda/travis-ci-meteor-packages/master/configure.sh | /bin/sh
  - yarn global add gulp-cli meteor-build-client electron@1.3.5
  - yarn

script:
  - 'if [ "$TRAVIS_BRANCH" = "develop" ]; then
        unset CSC_KEY_PASSWORD
        unset CSC_LINK
    fi'  # no macOS code-signing (production certificate) on develop branch
  - travis_wait 60 gulp mist --platform $GULP_PLATFORM

after_success:
  - gulp mist-checksums --platform $GULP_PLATFORM

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/33972d9e627a142c57a6
    on_success: change
    on_failure: always
    on_start: never
