sudo: required
dist: trusty

language: node_js
node_js:
  - "4"

branches:
  only:
    - develop

cache:
  timeout: 1000
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.meteor

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y icnsutils graphicsmagick xz-utils

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
  - "curl https://install.meteor.com/ | sh"
  - "npm install -g meteor-build-client"
  - "gulp update-nodes --platform linux"

script:
  - "npm run ci"

notifications:
  email:
    - EMAIL
